### ISSUE TITLE
[SFX] Cog now fails / times out upon loading

### ISSUE THREAD

**Issue by kaodhagain** [baiumbg/useless-cogs#21] opened 2020-12-16 02:06 UTC
When I try to load the sfx cog with the latest Red, I now get a timeout:

https://pastebin.com/DPa4tX5u

**Comment by baiumbg** [comment] 2020-12-16 18:33
Hey @doppletronica,

Can you run `pip freeze` and post the output for me, please?
Looks like you have an outdated version of the gtts pip package.

**Comment by kaodhagain** [comment] 2020-12-18 05:59
(red) pi@raspberrypi:~ $ pip freeze
aiohttp==3.6.2
aiohttp-json-rpc==0.13.2
aiosqlite==0.15.0
appdirs==1.4.4
apsw-wheels==3.30.1.post3
async-timeout==3.0.1
attrs==19.3.0
Babel==2.8.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
contextlib2==0.6.0.post1
discord.py==1.5.1
distro==1.5.0
fuzzywuzzy==0.18.0
idna==2.10
Markdown==3.2.2
multidict==4.7.6
python-Levenshtein-wheels==0.13.1
pytz==2020.1
PyYAML==5.3.1
Red-DiscordBot==3.4.3
Red-Lavalink==0.7.1
schema==0.7.2
tqdm==4.48.0
typing-extensions==3.7.4.2
uvloop==0.14.0
websockets==8.1
yarl==1.5.1

**Comment by baiumbg** [comment] 2020-12-18 10:31
@doppletronica Oh, I forgot Red actually installs cog requirements in its own lib directory.

Can you try running `[p]cog update`?
If it says they're all up to date, try reinstalling sfx.

The issue is caused by an outdated gtts python package, which is used by sfx.
Just need to find a way to update it.

**Comment by MayhemBill** [comment] 2020-12-22 20:51
I recently started getting this issue as well, is there any known fix for it?

**Comment by baiumbg** [comment] 2020-12-22 23:09
@MayhemBill The problem stems from an outdated version of gtts.
I experienced a similar issue a few weeks back and fixed it by installing the package globally (in Red's venv).
Red handles cog dependencies in a weird way and I'm not sure how you can force a dependency update.

So yeah, try installing the `gtts` package globally in Red's venv - `pip install gTTS`.
If you already have it installed for some reason, upgrade it - `pip install --upgrade gTTS`.

**Comment by MayhemBill** [comment] 2020-12-22 23:11
Yeah manually installing gTTS fixed it. Thanks

**Comment by baiumbg** [comment] 2020-12-22 23:12
Thanks for confirming.
Closing.

**Closed as completed by baiumbg** 2020-12-22 23:12 UTC
